controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pid_controller:
      type: pid_controller/PidController 

    swivel_position_controller:
      type: position_controllers/JointGroupPositionController
    
    joint_position_controller:
      type: position_controllers/JointGroupPositionController

    crane_homing_controller:
      type: crane_controllers/CraneHomingController

    crane_homing_controller:
      type: crane_controllers/CraneAttitudeController

crane_homing_controller:
  ros__parameters:
    command_interface: home
    
crane_attitude_controller:
  ros__parameters:
    command_interface: home
    


joint_position_controller:
  ros__parameters:
    joints:
      - swivel_joint
      - LG_lin_joint
      - RG_lin_joint

swivel_position_controller:
  ros__parameters:
    joints:
      - swivel_joint
    
pid_controller:
  ros__parameters: 
    dof_names: 
     - swivel_joint

    command_interface: position
    reference_and_state_interfaces:
      - position

    gains:
      swivel_joint:
        p: 10.0
        i: 0.0
        d: 0.1

