controller_manager:
  ros__parameters:
    update_rate: 100

    manipulator_controller:
      type: joint_trajectory_controller/joint_trajectory_controller
    
    joint_state_broadcaster:
      tpye: joint_state_broadcaster/JointStateBroadcaster

    # Manipulator controller
manipulator_controller:
  ros__parameters:
      joints:
        - ur10e_shoulder_pan_joint
        - ur10e_shoulder_lift_joint
        - ur10e_elbow_joint
        - ur10e_wrist_1_joint
        - ur10e_wrist_2_joint
        - ur10e_wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
