# Default initial positions for hb_robot's ros2_control fake system

initial_positions:
  ur10e_elbow_joint: 0
  ur10e_shoulder_lift_joint: 0
  ur10e_shoulder_pan_joint: 0
  ur10e_wrist_1_joint: 0
  ur10e_wrist_2_joint: 0
  ur10e_wrist_3_joint: 0