# Goal
geometry_msgs/Pose center_pose

float64 range_x
float64 range_y
uint8 num_viewpoints

float64 pos_tol
float64 orn_tol

float64 max_ang_vel
uint32 num_candidates
uint32 sample_attempts
---
# Result
bool success

uint8 SUCCESS=0
uint8 PLANNING_FAILED=1
uint8 MOTION_FAILED=2
uint8 STABILITY_TIMEOUT=3
uint8 ACQUISITION_FAILED=4
uint8 REGISTRATION_FAILED=5
uint8 CANCELLED=6

uint8 result_code

uint8 scene_id
uint32 viewpoints_captured
string message
---
# Feedback
uint32 current_viewpoint
uint32 total_viewpoints
geometry_msgs/Pose current_pose

uint8 PLANNING=0
uint8 MOVING=1
uint8 SETTLING=2
uint8 ACQUIRING=3
uint8 REGISTERING=4

uint8 phase
uint8 samples_acquired